### ISSUE TITLE
ansible not setting the default

### ISSUE THREAD

**Issue by rjrobinson** [rvm/rvm1-ansible#106]
I thought this installed correctly but, apparently, no default ruby is being set. 
I get no fails on install, and I have even started over with a  fresh VM. 

``` yaml
/setup.yml

---
- hosts: alpha-sandbox
  become: true
  roles:
    - { role: rvm_io.rvm1-ruby,
        tags: ruby,
        rvm1_rubies: 'ruby-2.2.5',
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm',
      }
```

the bigger issue, thinking that this worked, my production env is kinda stalled. Am I missing something?
