### ISSUE TITLE
bundle install - bundle not found

### ISSUE THREAD

**Issue by davemckenna01** [rvm/rvm1-ansible#132]
I have successfully installed rvm, but I'm unable to "bundle install" from within my ruby project. The bundle bin is not found.

````
- name: Install Repo Deps (From Gemfile)
  become: true
  become_user: '{{ ansible_user }}'
  command: bundle install
  args:
    chdir: "{{ code_dir }}/{{ item.name }}"
  with_items: "{{ repos|byattr('lang', 'ruby') }}"
````
results in:

`"[Errno 2] No such file or directory"`

````
- name: Install Repo Deps (From Gemfile)
  become: true
  become_user: '{{ ansible_user }}'
  shell: bundle install
  args:
    chdir: "{{ code_dir }}/{{ item.name }}"
  with_items: "{{ repos|byattr('lang', 'ruby') }}"
````
results in:

`"/bin/sh: 1: bundle: not found"`

But when I shell in to my vagrant box, bundle works fine, I can bundle install:

````
$ which bundle
/home/vagrant/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle
````

The Ansible bundle module also doesn't work. I have to explicitly specify the executable, and then it errors with this:

````
- name: Install Repo Deps (From Gemfile)
  bundler:
    state: present
    chdir: "{{ code_dir }}/{{ item.name }}"
    executable: /home/vagrant/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle
  with_items: "{{ repos|byattr('lang', 'ruby') }}"
````

`error: "/usr/bin/env: ruby_executable_hooks: No such file or directory"`

Any ideas what's up?
