### ISSUE TITLE
Problem install rubies

### ISSUE THREAD

**Issue by Evgeniy28** [rvm/rvm1-ansible#134]
My platform: fresh install of Ubuntu 14.04 on a VirtualBox VM using Vagrant on an OS X host.

RVM install without problem.
```sh
# path: /home/deployer/
rvm -v
rvm 1.28.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```
My playbook:
```yml
  vars:
    user: 'deployer'
    home_path: '/home/{{ user }}'
    rvm_path: '{{ home_path }}/.rvm'

  roles:
    - role: rvm_io.ruby
      tags: ruby
      become: yes
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '{{ rvm_path }}'
      rvm1_user: '{{ user }}'
      rvm1_rvm_version: 'stable'
      rvm1_rubies: ['ruby-2.3.3']
      rvm1_bundler_install: True
```
I'm waiting for a few hours, but nothing happens:
```sh
......
TASK [rvm_io.ruby : Configure rvm] *********************************************
skipping: [default] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [rvm_io.ruby : Detect if rubies are installed] ****************************
ok: [default] => (item=ruby-2.3.3) => {"changed": false, "cmd": ["/home/deployer/.rvm/bin/rvm", "ruby-2.3.3", "do", "true"], "delta": "0:00:00.276315", "end": "2017-01-18 09:51:53.383389", "failed": false, "failed_when_result": false, "item": "ruby-2.3.3", "rc": 2, "start": "2017-01-18 09:51:53.107074", "stderr": "Ruby ruby-2.3.3 is not installed.", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [rvm_io.ruby : Install rubies] ********************************************

```
What could be the reason?
