### ISSUE TITLE
rvm.sh no longer installed?

### ISSUE THREAD

**Issue by fields** [rvm/rvm1-ansible#135]
I'm migrating from using the rvm_io.rvm1-ruby galaxy role to using rvm_io.ruby, on centos. Previously, this role installed /etc/profile.d/rvm.sh so that rvm was started at login, but it seems that for a fresh machine where I've only used the rvm_io.ruby role, this file does not exist. Was this removed, and is there an alternate mechanism that should be used?

Thanks!

**Comment by saimonsharif** [comment]
Hi @fields, were you able to find a solution to this? I'm running into this now where `/etc/profile.d/rvm.sh` is only installed after running the galaxy role again.

**Comment by mehyedes** [comment]
I have hit the same issue, where the file is not installed.
Had to add another task to update `.bash_profile` for my user:
```
  - name: Update jenkins user startup files for rvm
    lineinfile:
      dest: /home/USER/.bash_profile
      line: "source $HOME/.rvm/scripts/rvm"
      regexp: "^source.*rvm$"
      state: present
      insertafter: EOF
      owner: USER
    tags: ruby
```
