### ISSUE TITLE
Latest value from rvm1_rubies even if rvm1_default_ruby_version is set

### ISSUE THREAD

**Issue by bolshakov** [rvm/rvm1-ansible#163]
Inventory file:

```yml
app:
  hosts:
    127.0.0.1:
      rvm1_rubies:
        - "ruby-2.1.1"
        - "ruby-2.3.5"
      rvm1_default_ruby_version: "ruby-2.1.1"
```
My playbook looks like this:

```yml
- hosts: app
  roles:
    - rvm_io.ruby
    - my_role
```

In `my_role` I use `rvm1_default_ruby_version` value to configure apache. I expect it is `ruby-2.1.1`, but actually it is to `ruby-2.3.5`. 

I factored tests app to reproduce the issue and printed `rvm1_default_ruby_version` before, inside and after my role. It prints `ruby-2.1.1`, `ruby-2.3.5` and `ruby-2.1.1`. I expect it is `ruby-2.1.1`.

Possibly related issue https://github.com/rvm/rvm1-ansible/issues/34
