### ISSUE TITLE
Suggestion: rvm1_symlink_to in defaults

### ISSUE THREAD

**Issue by meierw** [rvm/rvm1-ansible#195]
I think it would be a good idea to move `rvm1_symlink_to` (and most likely `rvm1_symlink_binaries` and `rvm1_symlink_bundler_binaries`) to `defaults` instead of `vars`.

The reasoning being - I recently had a use case where I needed to override this variable from `/usr/local/bin` to `/bin`. And first I tried this approach:
```yaml
   - role: rvm.ruby
      vars:
        rvm1_rubies: [ruby-2.5.3]
        rvm1_user: root
        rvm1_install_path: /usr/local/rvm
        rvm1_symlink_to: /bin
        rvm1_install_flags: --auto-dotfiles
        rvm1_gpg_key_server: hkp://p80.pool.sks-keyservers.net:80
```
Which didn't work. The role still copied the symlinks to `/usr/local/bin`

But afterward I tried one of the posted examples
```yaml
    # have to use this yaml object notation to assign variables
    # since the `rvm1_symlink_to` is in `vars` instead of `defaults`
    - { role: rvm.ruby,
        rvm1_rubies: [ruby-2.5.3],
        rvm1_user: root,
        rvm1_install_path: /usr/local/rvm,
        rvm1_symlink_to: /bin,
        rvm1_install_flags: --auto-dotfiles,
        rvm1_gpg_key_server: 'hkp://p80.pool.sks-keyservers.net:80' }
```
And it worked.

Obviously Ansible parses these two notation methods differently.

But now I have a playbook, where most roles use the first notation, because I find it more neat (less commas and quotes) and this one role use a different notation. Also I have to leave a comment for other developers that this is intentional and they shouldn't try to "clean it up" and then break it.

**Comment by tvw** [comment]
Yeah, the yaml notation used here is very strange.

When you want to have

```yaml
# have to use this yaml object notation to assign variables
# since the `rvm1_symlink_to` is in `vars` instead of `defaults`
- { role: rvm.ruby,
    rvm1_rubies: [ruby-2.5.3],
    rvm1_user: root,
    rvm1_install_path: /usr/local/rvm,
    rvm1_symlink_to: /bin,
    rvm1_install_flags: --auto-dotfiles,
    rvm1_gpg_key_server: 'hkp://p80.pool.sks-keyservers.net:80' }
```

it should look like this:

```yaml
# have to use this yaml object notation to assign variables
# since the `rvm1_symlink_to` is in `vars` instead of `defaults`
- name: Configure servers with ruby support for single user
  hosts: all
  roles:
  - role: rvm.ruby
    tags: ruby
    rvm1_rubies:
    - ruby-2.3.1
    rvm1_user: ubuntu
```

Using [] or {} is bad style, though [xxx] for a one element array in a one-liner should be ok,
