### ISSUE TITLE
ruby 2.1.3 being set has default even though ruby-2.2.1 is being installed.

### ISSUE THREAD

**Issue by matiaskorhonen** [rvm/rvm1-ansible#34]
My playbook has these variables defined:

``` yaml

---
  vars:
    rvm1_rubies:
      - 'ruby-2.2.1'
```

Ruby 2.2.1 is being installed as it should, but when it comes time to set the default Ruby, for some reason Ruby 2.1.3 is being selected. As 2.1.3 isn't installed on the system, this breaks the rest of the playbook.
- ansible 1.8.4
- rvm1-ansible at aefe5b0556c793707dde6ba99f2d23ec27721454
- Installing on RHEL 7.1

Ansible log output with `-vvvv` (server name redacted): https://gist.github.com/matiaskorhonen/f98980dfa5aa369479bc

**Comment by nickjj** [comment]
Is this with a clean installation on the system where `2.1.3` was never once on the system?

**Comment by matiaskorhonen** [comment]
It was there but was removed.

I removed every trace of it that I could find, including completely removing RVM itself.

The only way that I could get 2.2.1 to be the default version was by overriding the `rvm1_default_ruby_version ` variable: https://github.com/rvm/rvm1-ansible/compare/master...kiskolabs:master

**Comment by nickjj** [comment]
There must have been something left over for it to pick 2.1.3 but in either case it should have set 2.2.1. Thanks for the report.

**Comment by paulogeyer** [comment]
having a similar issue here, I've added 2.1.5 to the rubies list, but only 2.1.3 is installed

```
---

- name: Install rvm and ruby 2.1.5
  rvm1_rubies:
    - 'ruby-2.1.5'
  rvm1_user: 'crawlers'
  rvm1_version: 'stable'
  rvm1_rvm_check_for_updates: True
  rvm1_install_flags: '--auto-dotfiles --user-install'
  rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
```
