### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by dinapappor** [rvm/rvm1-ansible#45]
I can't get this role to work with FreeBSD 10.1 running on ec2 with newly spun ami. 

I get this:
```
TASK: [rvm_io.rvm1-ruby | Detect rvm binary] ********************************** 
fatal: [10.0.100.253] => Missing become password

FATAL: all hosts have already failed -- aborting
```

Relevant parts of the playbook:

```
---
- hosts: tag_env_ansiblelab:&tag_type_api
  remote_user: ec2-user
  become: yes
  become_method: su

  vars:
    ansible_python_interpreter: /usr/local/bin/python2.7
    rvm1_user: deploy
    rvm1_install_path: '/usr/home/deploy/.rvm'
    rvm1_install_flags: '--auto-dotfiles --user-install'

  pre_tasks:
    - pkgng: name=ca_root_nss state=present
    - pkgng: name=sudo state=present
    - pkgng: name=bash state=present
    - pkgng: name=gnupg state=present
    - user: name=deploy shell=/usr/local/bin/bash
    - name: Configure deploy sudoers file
      lineinfile: dest=/usr/local/etc/sudoers.d/deploy owner=root group=wheel mode=0440
                  line="deploy ALL=(ALL) NOPASSWD:ALL"
                  state=present
                  create=yes
                  validate='visudo -cf %s'

  tasks:
  - name: Bootstrap pkng
    raw: /usr/sbin/pkg -N
    register: pkg
    ignore_errors: True
  - raw: /usr/bin/env ASSUME_ALWAYS_YES=1 /usr/sbin/pkg bootstrap -f
    when: pkg|failed


  roles:
     - nginx
     - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
```

nginx does install fine.
