### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by rngadam** [rvm/rvm1-ansible#6]
I use a Squid proxy to accelerate repeated virtual machines install provisioned using Ansible.

There doesn't seem to be a way to set environment variables globally per playbook or role so bundler, gem and rvm all need to be set separately

This is how it works for rvm: http://rvm.io/workflow/proxy

For now, I'll set up a ~/.curlrc, but it would be nice if the rvm1.io role would take a var for this.

I have at least one other place I use proxy with the bundler by setting the environment variable so it would probably be similar to this:

```
    - name: with parallel install (see https://github.com/bundler/bundler/pull/2481)
      command: "{{rvm1_bundle}} install -j4"
      environment:
        http_proxy: "{{host_proxy}}"
        HTTP_PROXY: "{{host_proxy}}"
      tags: parallel_install
```
