### ISSUE TITLE
Gems installed by root user lands in `/root/.gem`

### ISSUE THREAD

**Issue by jumski** [rvm/rvm1-ansible#60]
I install some ruby with this dependency:

``` yaml

---
dependencies:
  - role: rvm_io.rvm1-ruby
    rvm1_rubies:
      - ruby-2.0.0-p643
    rvm1_default_ruby_version: ruby-2.0.0-p643
```

and later on install a gem with following task:

``` yaml
- name: install backup gem
  tags: focus
  gem: name=backup version=4.2 state=present executable=/usr/local/rvm/rubies/ruby-2.0.0-p643/bin/gem
```

them gem lands into `/root/.gem/ruby/2.0.0/gems/` instead of rvm's path. There is only a wrapper in `/usr/local/rvm` for `backup` binary.

I've tried with manually overriding environment like this:

``` yaml
  environment:
    PATH: "/usr/local/rvm/gems/{{default_ruby}}/bin:/usr/local/rvm/gems/{{default_ruby}}@global/bin:/usr/local/rvm/rubies/{{default_ruby}}/bin:{{ansible_env.PATH}}"
    GEM_HOME: /usr/local/rvm/gems/{{default_ruby}}
    GEM_PATH: /usr/local/rvm/gems/{{default_ruby}}:/usr/local/rvm/gems/{{default_ruby}}@global
```

but without any luck.

Is it even possible to use `gem_module` to install gems for rvm rubies? Or i should fallback to some `shell:` with `creates:` trickery?

Thanks for any help!

My versions:

```
ansible 1.9.3
rvm1-ansible v1.3.7
```
