### ISSUE TITLE
errors in rubies task

### ISSUE THREAD

**Issue by alettieri** [rvm/rvm1-ansible#78]
I'm receiving the following error during the Install rubies task:

`error while evaluating conditional: rvm1_rubies and item.rc != 0`

When looking at the *tasks/rubies.yml* file:

In task _[Install rubies](https://github.com/rvm/rvm1-ansible/blob/master/tasks/rubies.yml#L13)_:

```yaml
 when: rvm1_rubies and item.rc != 0
```

It seems that the dict attribute `rc` may be missing at times. 

It works fine when there's a fallback value.

```yaml
 when: rvm1_rubies and item.rc|default(0) != 0
```

In task _[Select default ruby](https://github.com/rvm/rvm1-ansible/blob/master/tasks/rubies.yml#L24)_:

The stdout may need a default fallback as well. It threw errors as well.
```yaml
when: detect_default_ruby_version.stdout == '' or
        rvm1_default_ruby_version not in detect_default_ruby_version.stdout
```

works fine when changed to:

```yaml
when: detect_default_ruby_version.stdout|default() == '' or
        rvm1_default_ruby_version not in detect_default_ruby_version.stdout
```

Fixing these two lines solved my problem.

Here are some _rvm1_ variables I'm using in case it helps:

```yaml
rvm1_rubies:
  - 'ruby-2.2.0'
rvm1_install_flags: '--auto-dotfiles --user-install'
rvm1_rvm_version: 'stable'
rvm1_rvm_check_for_updates: True
```
